import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });
import ContextProvider from "@/api/context";

export const metadata: Metadata = {
  title: "Micro Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <ContextProvider>
      <body className={inter.className}>
        <Header/>
            {children}
      </body>
      </ContextProvider>
    </html>
  );
}
